default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  host: <%= ENV["DATABASE_HOST"] %>


development:
  <<: *default
  database: <%= ENV["DEV_DATABASE_NAME"] %>

test:
  <<: *default
  database: <%= ENV["TEST_DATABASE_NAME"] %>

production:
  <<: *default
  database: <%= Aws::SSM::Client.new.get_parameter(name: 'database_name', with_decryption: true).parameter.value %>
  username: <%= Aws::SSM::Client.new.get_parameter(name: 'database_username', with_decryption: true).parameter.value %>
  password: <%= Aws::SSM::Client.new.get_parameter(name: 'database_password', with_decryption: true).parameter.value %>
  host: <%= Aws::SSM::Client.new.get_parameter(name: 'database_host', with_decryption: true).parameter.value %>

