default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: "6seogFFOEKgi%%hu245134KGlad"
  host: localhost

development:
  <<: *default
  database: spa_portfolio_development

test:
  <<: *default
  database: spa_portfolio_test

production:
  <<: *default
  database: spa_portfolio_production
  username: backend
  password: <%= ENV['BACKEND_DATABASE_PASSWORD'] %>

