source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.0.3'

gem 'rails', '~> 6.1.7'
gem 'mysql2', '~> 0.5'
gem 'puma', '~> 5.0'
gem 'bootsnap', '>= 1.4.4', require: false
gem 'rack-cors'
gem 'bullet'
gem 'aws-sdk-s3'
gem 'httparty'
gem 'rspec-rails'
gem "factory_bot_rails"
gem 'rails-i18n', '~> 6.0.0'
gem 'aws-sdk-ssm', '~> 1.0'
gem 'ffi', '1.16.0'
gem 'aws-sdk-ses', '~> 1'
gem 'aws-sdk-rails'

group :development, :test do
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  gem 'dotenv-rails'
end

group :development do
  gem 'listen', '~> 3.3'
  gem 'spring'
end

group :test do
  gem 'database_cleaner'
  gem 'shoulda-matchers'
end

gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

group :production do
  gem 'unicorn'
  gem "capistrano", "~> 3.10"
  gem 'capistrano-rbenv', '~> 2.2'
  gem 'capistrano-rbenv-vars', '~> 0.1'
  gem 'capistrano-bundler'
  gem "capistrano-rails", "~> 1.6"
  gem 'capistrano3-unicorn'
end
